# Introduction
Student ID Number: 230002756

GitHub Repository: https://github.com/lucy-wagz/Assessment_2_Repository

This assessment intends to showcase my exploration into Python. With some previous python knowledge from highschool and private instruction, I utilized previously learned skills in a new context: Spatial Analysis.

Due to the large file size of the full, final notebook even when I cleared my intermediary outcomes and library installs, I have split my notebook intwo 2 Colab Notebooks. This notebook contains Part 1: Python Basics and Part 2: Pandas and NumPy.

# Part 1: Python Basics

## 1.1


In [1]:
10+20

30

In [2]:
# in Google Colab, pressing the D key 2 times does not delete

## 1.2

In [3]:
# list of numbers
numbers = [80,90,95,87,82]

In [4]:
# use the workbook instructions and the def (calculate_average) for the list of numbers to find the average
# in order to find the average, we must write a function finding both the sum of the numbers and a functions finding the amount of numbers
# the average = total / amount

def calculate_average (num_list):
    total = sum(num_list)
    count = len(num_list)
    average = total / count
    return average

# then, we must print the result using the print function

result = calculate_average(numbers)
print("The average is:", result)

The average is: 86.8


## 1.3

The pandas library is necessary to work with spreadsheets/CSV files, geopandas (gpd) is so that we can work with geographical data (points, polygons, spatial operations) in this case, we are assessing a world cities shapefile and a CSV file about world cities as well.

## 1.4

In [5]:
 # correct code:

name = 'Dave'
dogs = 0
print('My name is', name, 'and I own', dogs, 'dogs.')

My name is Dave and I own 0 dogs.


Indentation only makes sense when the code is "inside" of something (e.g., an if True statement) or part of a separate block/ another function or loop.

## 1.5

In [6]:
a = "Taco "
b = "time"
c = a + b
print(c)

Taco time


Now in the following code cell, I created a script where I print string and integer variables.

In [7]:
a = "Lucy"
b = " is a student at St Andrews."
c = a + b
print (c)

Lucy is a student at St Andrews.


## 1.6

The provided code was incorect because of the indentation of the code blocks. Because the line'temperature = 10' is not nested within another block, there is no need for its indentation.

Below is the correct indentation for the code block.

In [8]:
season = "Winter"
temperature = 10

if season == "Winter":

     if temperature > 7:
         print("No need for winter jacket!")

     else:
         print("It might be cold! Wear a proper jacket!")

elif season == "Summer":

     if temperature > 20:
         print("It's warm! Time to wear shorts!")

     else:
         print("Well this is Finland, better wear long trousers!")
else:
     print("Check the weather forecast!")

No need for winter jacket!


In the following code cell, I have created a similar script with several nested *if* conditions cimilar to the example above.

In [9]:
season = "Spring"
temperature = 18

if season == "Spring":

    if temperature > 18:
        print("You don't need a sweater today.")

    else:
        print("You should wear a light sweater just in case.")

elif season == "Autumn":

    if temperature < 15:
        print("It's getting cold, you should put on another layer")

    else:
        print("You dont necessarily need another layer, but it would be good to have")

else:
    print("Check the weather forecast.")

You should wear a light sweater just in case.


## 1.7

In [10]:
def celsius_to_fahr(temp):
    return 9 / 5 * temp + 32

We know that the 1 mile is equal to 1.60934 kilometers, so creating a function will utilize (miles x kilometers).

In [11]:
# this defines what the name will correlate to in the printed product

def miles_to_kms(miles):
    return miles * 1.60934

In [12]:
# in this case, I illustrated what 1,5, and 10 miles is in kilometers

print(miles_to_kms(1))
print(miles_to_kms(5))
print(miles_to_kms(10))

1.60934
8.0467
16.0934


## 1.8

In [13]:
# n will be the number of the multiplication table (e.g., a table for 3s)
# the range (1,11) means that the loop will start at 1 and go to 10, running the code 10 times

def multiplication_table(n):
    for i in range(1,11):
        print(n,"x",i,"=",n*i)

In [14]:
# table for 3

print("Multiplication table for 3:")
multiplication_table(3)

Multiplication table for 3:
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


In [15]:
# table for 12

print("Multiplication table for 12:")
multiplication_table(12)

Multiplication table for 12:
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120


## 1.9

In [16]:
# I altered the example to showcase new lunch components

lunch = [
    'Chips',
    'Chips',
    'Sandwich',
    'Wrap',
    'Potato',
    'Wrap',
    'Sandwich',
    'Wrap',
    'Tea',
    'Potato',
    'Potato',
    'Coffee'
]

In [17]:
# this code goes through each item in this list and counts how many times the item appears, as seen below

counts = {}

for item in lunch:
    if item not in counts:
        counts[item] = 1
    else:
        counts[item] += 1

print(counts)

{'Chips': 2, 'Sandwich': 2, 'Wrap': 3, 'Potato': 3, 'Tea': 1, 'Coffee': 1}


## 1.10

In [18]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [19]:
# in ArcGIS, the code was saved to my H drive and uploaded from there:
  # H:\GG3209\week_5_Python\Latest_earthquake_world.csv
# I then imported pandas as seen below

import pandas as pd

# however, Colab must have files uploaded from the drive, so this is my pathway:

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/python_basics/Latest_earthquake_world.csv")
df.head(30)

Mounted at /content/drive


time   latitude   longitude    depth   mag magType  \
0   2023-02-23T08:01:02.881Z  38.128000   73.218400   10.000  4.70      mb   
1   2023-02-23T06:55:34.020Z  18.794600  -63.920500   10.000  3.67      md   
2   2023-02-23T06:50:49.137Z  38.487900   72.812200   10.000  4.50      mb   
3   2023-02-23T06:18:13.280Z  -8.548300  -77.625400   66.540  4.70      mb   
4   2023-02-23T03:36:09.429Z -18.287000 -177.826100  524.983  4.90      mb   
5   2023-02-23T03:18:57.663Z -30.391600  -71.685600   34.097  4.40      ml   
6   2023-02-23T02:18:00.671Z  38.336200   73.106700   10.000  4.70      mb   
7   2023-02-23T02:07:46.940Z  38.182200   73.234600   10.000  4.80      mb   
8   2023-02-23T02:03:42.690Z  18.079300  -68.088800   78.000  3.54      md   
9   2023-02-23T01:35:57.658Z  38.182400   73.279400   10.000  4.90      mb   
10  2023-02-23T01:33:25.965Z  59.261500 -153.135600   77.400  2.50      ml   
11  2023-02-23T01:06:05.337Z  38.180400   72.782900   10.000  4.60      mb   
12  2023-02-23T00:55:14.540Z  38.147400   72.982400   10.000  5.00      mb   
13  2023-02-23T00:37:40.397Z  38.072600   73.207700   20.522  6.80     mww   
14  2023-02-22T23:44:02.170Z  39.145168 -123.260002    1.870  2.91      md   
15  2023-02-22T23:14:55.147Z  64.931800 -147.252000  148.800  2.90      ml   
16  2023-02-22T23:06:22.156Z  53.653800   98.458200    9.707  4.70      mb   
17  2023-02-22T22:05:53.566Z  10.179100  125.063300   10.000  4.60      mb   
18  2023-02-22T21:39:43.663Z  59.184300 -151.517400    2.000  2.50      ml   
19  2023-02-22T21:18:44.007Z  23.963800  121.774100    8.774  4.40      mb   
20  2023-02-22T20:01:57.120Z  38.820999 -122.853996    2.640  3.22      ml   
21  2023-02-22T18:22:12.682Z  38.157700 -117.889100    8.700  3.50      ml   
22  2023-02-22T18:18:25.802Z -35.700800  -73.161700   35.000  4.30      mb   
23  2023-02-22T17:47:55.177Z -35.748700  -73.151800   35.000  4.00      mb   
24  2023-02-22T15:56:47.583Z  61.257000 -150.320300  250.000  2.50      ml   
25  2023-02-22T15:51:39.859Z -30.038900  -72.203500   12.059  4.00     mwr   
26  2023-02-22T15:48:21.690Z  40.555832 -124.212669   14.430  3.21      ml   
27  2023-02-22T15:18:06.170Z  18.231000  -68.260500   96.000  3.76      md   
28  2023-02-22T14:11:28.720Z  19.904167 -155.158333   43.590  3.24      ml   
29  2023-02-22T13:12:26.230Z  18.798667  -65.057500   17.130  3.09      md   

      nst     gap      dmin     rms  ...                   updated  \
0    75.0   55.00  1.745000  0.6600  ...  2023-02-23T08:35:43.040Z   
1    19.0  228.00  1.126400  0.5000  ...  2023-02-23T08:02:57.172Z   
2    21.0  171.00  1.264000  0.5600  ...  2023-02-23T07:28:35.040Z   
3    44.0  154.00  3.503000  0.4700  ...  2023-02-23T07:15:40.040Z   
4    40.0   63.00  3.626000  0.6700  ...  2023-02-23T03:50:54.040Z   
5    33.0  187.00  0.285000  0.9400  ...  2023-02-23T03:30:52.786Z   
6    52.0   60.00  1.529000  0.9400  ...  2023-02-23T02:37:56.040Z   
7    21.0  180.00  1.712000  0.8100  ...  2023-02-23T02:22:17.040Z   
8    14.0  234.00  0.157700  0.2000  ...  2023-02-23T02:42:39.960Z   
9    27.0  166.00  1.735000  0.7000  ...  2023-02-23T01:49:27.040Z   
10    NaN     NaN       NaN  0.5700  ...  2023-02-23T01:35:49.711Z   
11   20.0  163.00  1.506000  0.6400  ...  2023-02-23T01:27:51.040Z   
12   84.0   80.00  1.618000  0.8400  ...  2023-02-23T01:13:06.040Z   
13  128.0   20.00  1.783000  0.9600  ...  2023-02-23T05:49:51.952Z   
14   26.0   68.00  0.068420  0.0800  ...  2023-02-23T06:29:31.972Z   
15    NaN     NaN       NaN  1.2900  ...  2023-02-22T23:18:24.121Z   
16   64.0   68.00  3.724000  0.6700  ...  2023-02-23T00:02:22.040Z   
17   44.0  120.00  3.131000  0.4600  ...  2023-02-23T04:25:16.518Z   
18    NaN     NaN       NaN  1.0800  ...  2023-02-22T21:42:36.481Z   
19   34.0   83.00  0.266000  0.5100  ...  2023-02-22T23:06:06.040Z   
20   52.0   49.00  0.006912  0.0500  ...  2023-02-23T03:23:48.835Z   
21   13.0   80.53  0.059000  0.1197  ...  2023-02-23T02:03:07.570

# Part 2: Pandas and NumPy

## 2.0


In [20]:
import numpy as np

## 2.1

In [21]:
# the function arr1 = np.ones(10) creates an array entirely of 1s
  # the argument = 10 which means in this case there are 10 1s

# the function arr2 = np.ones(1,21) creates an array of integers 1 to 20
  # the function is classified in parenthesis as (start, stop) meaning that it will start at the nuber 1 and end at the number before 21

# the function arr3 = np.ones((5,5), dtype=int) creates a matrix of 5x5 1s
  # np.ones((5,5)) is the function for creating a matrix with 5 rows and 5 columns
  # dtype = int forces the 1 to be integers instad of floats -- this is necessary because we are indexing 1s, not counting them

arr1 = np.ones(10)
arr2 = np.arange(1,21)
arr3 = np.ones((5,5), dtype = int)
print(arr1)
print(arr2)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2

In [22]:
# I begin by importing numpy as np

import numpy as np

# similar to the above function, i norder to print arr1, I had to define what it is
  # in this case, it prints a 3D matrix of 3x3x3 ()
arr1 = np.random.randn(3,3,3)
print(arr1)

[[[-0.63350091  1.46077815 -0.06751028]
  [ 2.13945436  0.56900943 -0.40098232]
  [-1.86624761  0.5069541  -0.8186505 ]]

 [[ 1.76039604 -0.92482067 -0.37967965]
  [-0.73061322 -0.72317316  0.01863306]
  [-0.42969439  0.61049337 -0.87167216]]

 [[-1.37085787 -1.19532097 -0.49251005]
  [-1.48970176 -0.30269069 -0.04051477]
  [ 0.74218169 -0.94684674 -0.33093148]]]


In [23]:
# this reshapes the array into a list of 27 randm numbers, as opposed to a 3x3x3 matrix

arr2 = arr1.reshape(27,)
print(arr2)

[-0.63350091  1.46077815 -0.06751028  2.13945436  0.56900943 -0.40098232
 -1.86624761  0.5069541  -0.8186505   1.76039604 -0.92482067 -0.37967965
 -0.73061322 -0.72317316  0.01863306 -0.42969439  0.61049337 -0.87167216
 -1.37085787 -1.19532097 -0.49251005 -1.48970176 -0.30269069 -0.04051477
  0.74218169 -0.94684674 -0.33093148]


## 2.3

In [24]:
# this produces 20 evenly spaced numbers between 1 and 10
  # (start, end, number of points)

arr = np.linspace(1,10,20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

In [25]:
# arrange: numbers 1-25
# reshape: puts this in a 5x5 matrix

a = np.arange(1, 26).reshape(5, 5)

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
# this indexes a part of the matrix by [row, column], in this instance 3 and 4
# row 3, column 4 = 20

a[3,4]

print(a[3,4])

20


In [27]:
# the colon function (:) indicates all rows between numbers -- in this case, 1-5
# after the comma, the 3:5 indicates which colums to pick numbers from -- in this case, 3-5

a[1:5, 3:5]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [28]:
# an empty (colon only) number within the brackets indicates that an entire row is to be selected, in this case, row 1

a[1, :]

array([ 6,  7,  8,  9, 10])

## 2.5

In [29]:
# using the sum function calculates the sum of all numbers in the array

a.sum()

np.int64(325)

## 2.6

In [30]:
# in order to calculate the sum of 1 row only, the row must be defined as an axis
# for row 1, t would be axis = 1

a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

## 2.7

In [31]:
mean_value = a.mean()
print(mean_value)

13.0


In [32]:
# the mask must print all values in the array that are greater then 13

mask = a > mean_value

a[mask]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

## 2.8

In [33]:
import pandas as pd

## 2.9

In [34]:
import pandas as pd

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

df = pd.read_csv(url)

df.head()

country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96

## 2.10

In [35]:
# using the function df.shape, we can see how many rows and columns are in the dataset

df.shape
rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 1430
Number of columns: 4


## 2.11

In [36]:
# using the .mean() function I was able to find the mean between the countries, and then I rounded it to 2 decimal places

mean_co2 = df['co2_emmission'].mean().round(2)
print("Mean CO2 emission:", mean_co2)

Mean CO2 emission: 74.38


## 2.12

In [37]:
# maximum CO2 emissions from one country

df['co2_emmission'].max()

1712.0

In [38]:
# .loc selects by index - as we are trying to find which country is responsible for the high CP2 emissions
# if maximum emissions are in row 2 (as seen in the table) it can be inferred that Argentina produces the most CO2
df.loc[df['co2_emmission'].idxmax()]

country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object

In [39]:
max_value = df['co2_emmission'].max()
max_row = df.loc[df['co2_emmission'].idxmax()]

# I figured out a way to print a more accessible view of the max emissions, country responsble, and food product using the table/previously written code
print("Maximum CO2 emission:", max_value)
print("Country:", max_row['country'])
print("Food Category:", max_row['food_category'])

Maximum CO2 emission: 1712.0
Country: Argentina
Food Category: Beef


## 2.13

In [40]:
# by setting the co2_emmission category > 1000, it illustrates which countries in the dataset match that threshold
# using n.unique counts how many different countries fit this criteria and condenses it into 1 number

high_emitters = df[df['co2_emmission'] > 1000]['country'].nunique()
print("Number of countries emitting > 1000 kg CO2 per person, pear year:", high_emitters)

Number of countries emitting > 1000 kg CO2 per person, pear year: 5


## 2.14

In [41]:
# first, I assessed the different items within the 'food_category' column of data

df['food_category'].unique()

array(['Pork', 'Poultry', 'Beef', 'Lamb & Goat', 'Fish', 'Eggs',
       'Milk - inc. cheese', 'Wheat and Wheat Products', 'Rice',
       'Soybeans', 'Nuts inc. Peanut Butter'], dtype=object)

In [42]:
# the question asked us to assess what country consumes the least amount of beef per year, so i selected by item attribute with the following code

beef = df[df['food_category'] == 'Beef']

In [43]:
# I then used the .idxmin() function to assess where in the table the least amount of beef was consumed

least_beef = beef.loc[beef['consumption'].idxmin()]
least_beef

country          Liberia
food_category       Beef
consumption         0.78
co2_emmission      24.07
Name: 1410, dtype: object

In [44]:

# this filters so that 'beef' is the only "food_category" criteria that shows up
# additionally, some of the data was labelled 'BEEF, Beef, or beef' so I ran an aditional function to convert to lowercase
beef = df[df['food_category'].str.lower() == 'beef']

# this locates the row in which beef consumption is lowest
least_beef = beef.loc[beef['consumption'].idxmin()]

print("Country:", least_beef['country'])
print("Consumption:", least_beef['consumption'])

Country: Liberia
Consumption: 0.7799999999999999


## 2.15

In [45]:
# first I crated a list to only show meat in the 'food_category' column
meat_types = ['pork', 'poultry', 'fish', 'lamb & goat', 'beef']

# then, I filtered the dataset to only keep the meat types when collecting data from the dataset
# the smaller dataframe helps contain the values to only meat products and their corresponding data
meat_df = df[df['food_category'].str.lower().isin(meat_types)]

# the meat emissions selects the co2 emissions from just the meat dataframe and calculates the sum of all number
total_meat_emissions = meat_df['co2_emmission'].sum()

print("Total emissions from meat products:", total_meat_emissions)

Total emissions from meat products: 74441.13


## 2.16

In [46]:
import pandas as pd

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url)

In [47]:
# in order to assess emissions of non-meats, we must filter out the previoulsy used meat_types list

# the ~df is used as a NOT operator, essentially it flips the validity of the statement so that non-meats are included and meat_types are excluded
non_meat_df = df[~df['food_category'].str.lower().isin(meat_types)]

# similar to above, we run a .sum() function to find the total emissions from non-meat foods
total_non_meat_emissions = non_meat_df['co2_emmission'].sum()

print("Total non-meat emissions:", total_non_meat_emissions)

Total non-meat emissions: 31927.98


## 2.17 - World Cities Final Challenge

In [48]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [49]:
import pandas as pd

# here, I defined 'cities' as the CSV file provided
cities = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/final_challenge/world_cities.csv")

# .head() shows the first few rows of the dataframe as to not crowd the notebook with all rows
cities.head()

city    country    pop    lat    lon  capital
0  'Abasan al-Jadidah  Palestine   5629  31.31  34.34        0
1  'Abasan al-Kabirah  Palestine  18999  31.32  34.35        0
2        'Abdul Hakim   Pakistan  47788  30.55  72.11        0
3  'Abdullah-as-Salam     Kuwait  21817  29.36  47.98        0
4               'Abud  Palestine   2456  32.03  35.07        0

In [50]:
# in order to calculate the population in millions (pop_M), the original population column had to be divided by 1,000,000

cities["pop_M"] = cities["pop"] /1_000_000
cities.head()

city    country    pop    lat    lon  capital     pop_M
0  'Abasan al-Jadidah  Palestine   5629  31.31  34.34        0  0.005629
1  'Abasan al-Kabirah  Palestine  18999  31.32  34.35        0  0.018999
2        'Abdul Hakim   Pakistan  47788  30.55  72.11        0  0.047788
3  'Abdullah-as-Salam     Kuwait  21817  29.36  47.98        0  0.021817
4               'Abud  Palestine   2456  32.03  35.07        0  0.002456

In [51]:
# next, I dopped the now unnecessary 'pop' column as we now have the population displayed in millions

cities = cities.drop(columns=["pop"])
cities.head()

city    country    lat    lon  capital     pop_M
0  'Abasan al-Jadidah  Palestine  31.31  34.34        0  0.005629
1  'Abasan al-Kabirah  Palestine  31.32  34.35        0  0.018999
2        'Abdul Hakim   Pakistan  30.55  72.11        0  0.047788
3  'Abdullah-as-Salam     Kuwait  29.36  47.98        0  0.021817
4               'Abud  Palestine  32.03  35.07        0  0.002456

In [52]:
# next, i filtered the dataset to show me only cities starting with the first letter of my name, in this case, L for Lucy

# through research, I foud that .str.startswtith("L") runs a series of True/False tests on cities to see if they fit the qualification of starting with the letter L
cities_with_L = cities[cities["city"].str.startswith("L")]
cities_with_L

city  country    lat    lon  capital     pop_M
19596           L'Aigle   France  48.77   0.63        0  0.009218
19597          L'Alcora    Spain  40.07  -0.20        0  0.010418
19598         L'Alcudia    Spain  39.21  -0.51        0  0.010631
19599    L'Alfas del Pi    Spain  38.59  -0.11        0  0.014444
19600  L'Ametlla de Mar    Spain  40.90   0.80        0  0.006582
...                 ...      ...    ...    ...      ...       ...
21843       Lyublynets'  Ukraine  51.18  24.62        0  0.004201
21844          Lyuboml'  Ukraine  51.23  24.03        0  0.010391
21845          Lyubotyn  Ukraine  49.95  35.97        0  0.022162
21846        Lyubymivka  Ukraine  46.80  33.59        0  0.005733
21847         Lyudinovo   Russia  53.87  34.45        0  0.041253

[2252 rows x 6 columns]

In [53]:
# my chosen city is Lisbon in Portugal, and I achieved this by setting the city category == to Lisbon in the code

my_city = cities_with_L[cities_with_L["city"] == "Lisbon"]
my_city

city   country    lat   lon  capital     pop_M
21101  Lisbon  Portugal  38.72 -9.14        1  0.508209

In [54]:
# additionally, I printed a sentence illustrating my chosen city and what country it is in.

my_city1 = "Lisbon"
print("My chosen city is", (my_city1), "-- located in Portugal.")

My chosen city is Lisbon -- located in Portugal.


In [55]:
# this function selects the row in the dataset
my_city = cities[cities["city"] == "Lisbon"].iloc[0]

# next, i defined the name of the country for my selected city, which will also be used to define the other 4 most populated cities in the final dataset
country_name = my_city["country"]

# this function finds other cities that match the same country Lisbon is located in (Portugal)
country_cities = cities[cities["country"] == country_name]

# this function prints the dataset and sorts it by largest to smallest populations first
# the .head(5) selects the top 5 countries without displaying other ones
top5_country = country_cities.sort_values(by="pop_M", ascending=False).head(5)
top5_country

city   country    lat   lon  capital     pop_M
21101   Lisbon  Portugal  38.72 -9.14        1  0.508209
29631    Porto  Portugal  41.15 -8.62        0  0.246264
1214   Amadora  Portugal  38.75 -9.24        0  0.179486
5214     Braga  Portugal  41.55 -8.43        0  0.123367
34612  Setubal  Portugal  38.53 -8.89        0  0.118056

In [56]:
import os

folder = "/content/drive/MyDrive/Colab Notebooks/Assessment_2_230002756"
os.listdir(folder)


['Final_Challenge_Worldcities_230002756.ipynb',
 'Exercises_GeoPandas_Nov25_230002756.ipynb',
 'Lab Assignment 2 – GG3209 – Python for Spatial Analysis.ipynb',
 'Python_Spatial_Clustering_Exercises_230002756.ipynb',
 'Assessment_2_230002756_Final.ipynb']